---
title: "Personalized Dynamic Pricing with Machine Learning: High Dimensional Features and Heterogeneous Elasticity"
author: "[Gah-Yi Ban](https://www.gahyiban.com/)"
date: 2023-02-24
categories: [H23, Zoom]
draft: 
room: "Zoom"
time: 10h00
url: https://www.gahyiban.com/
---

# Résumé

We consider a seller who can dynamically adjust the price of a product at the individual customer level, by utilizing information about customers’ characteristics encoded as a $d$-dimensional feature vector. We assume a personalized demand model, parameters of which depend on $s$ out of the $d$ features. The seller initially does not know the relationship between the customer features and the product demand, but learns this through sales observations over a selling horizon of $T$ periods. We prove that the seller’s expected regret, i.e., the revenue loss against a clairvoyant who knows the underlying demand relationship, is at least of order $s\sqrt{T}$% under any admissible policy. We then design a near-optimal pricing policy for a “semi-clairvoyant” seller (who knows which $s$ of the $d$ features are in the demand model) that achieves an expected regret of order $s\sqrt{T}\log T$. We extend this policy to a more realistic setting where the seller does not know the true demand predictors, and show that this policy has an expected regret of order $s\sqrt{T} (\log d＋\log T)$, which is also near-optimal. Finally, we test our theory on simulated data and on a data set from an online auto loan company in the United States. On both data sets, our experimentation-based pricing policy is superior to intuitive and/or widely-practiced customized pricing methods such as myopic pricing and segment-then-optimize policies. Furthermore, our policy improves upon the loan company’s historical pricing decisions by 47% in expected revenue over a six-month period.

# Biographie

Dr. Gah-Yi Ban est professeur aggrégée à l’école de gestion de Imperial College à Londres et anciennement de la London Business School et de l’Université du Maryland. Elle détient un doctorat en recherche opérationnelle de l’Université de Californie à Berkeley (UCB) et sert en qualité de rédactrice ajointe de Management Science, M&amp;SOM et de Operations Research Letter. Ses intérêts de recherche sont en analytique des mégadonnées, plus spécialement la prise de décision dans des environnements incertains en haute-dimension avec des applications en gestion. Ses recherches ont été couronnées du prix Best OM Paper in Operations Research award en 2021.
