---
title: "Institutional Ownership and the Resolution of Financial Distress"
author: "[Jocelyn Martel](https://faculty.essec.edu/cv/fr-martel-jocelyn/)"
date: 2023-05-16
categories: [2022-2023]
draft: 
room: "[salle Xerox-Canada](https://www.hec.ca/campus/edifices/cote_sainte_catherine/1er_etage/salles_cours/xerox.html)"
time: "11h00"
url: https://faculty.essec.edu/cv/fr-martel-jocelyn/
---

# Résumé


We analyze the distressed firm's decision between Chapter 11 and an exchange offer. We construct a comprehensive data set on the financial characteristics and capital structure of 269 distressed firms, which, unlike previous studies, uses quarterly information and includes exhaustive data on equity and bond ownership by institutional investors. Logit regressions confirm that the firm's restructuring decision depends on its financial characteristics as well as the equity and bond ownership of institutional investors. The impact of ownership varies across categories of investors and according to whether they hold equity or bonds. In general, equity ownership favours exchange offers while we find mixed evidence for bond ownership. In particular, hedge funds have a positive impact on the likelihood of exchange offers through their equity holdings but none through their bond holdings. VC/PE firm holdings are also unique in that higher equity holdings are associated with exchange offers and higher bond holdings with Chapter 11. Finally, the magnitude of equity and bond institutional ownership depend on the quarter at which they are measured, confirming the importance of using quarterly data. This is joint work with Timothy C.G. Fisher and Lorenzo Naranjo.

# Biographie

Dr. Jocelyn Martel est professeur titulaire au département de finance de l'école de gestion ESSEC depuis 2012 et spécialiste de l'économétrie financière. Son champ d'expertise est en théorie financière, faillites, restructurations et évaluations d'entreprises. Il est co-directeur de la chaire Amundi en gestion du risque et des actifs. Il a défendu son habilitation à diriger des recherches à Cergy-Pontoise en 2008 et a obtenu une maîtrise et un doctorat en économie de l'Université de Montréal.
