---
title: "An Extended Validity Domain for Constraint Learning"
author: "[Samuel Burer](http://sburer.github.io/)"
date: 2024-02-02
categories: [2023-2024, GERAD]
draft: false
room: "salle [Budapest](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/budapest.html)"
time: "13h30"
url: http://sburer.github.io/
---

# Résumé

We consider embedding a (predictive) machine-learning model within a (prescriptive) optimization problem. In this setting, called constraint learning, the computed optimal solution may be too far from the training data, that is, in a region where the machine-learning predictions are less accurate. To correct for this, researchers have proposed the concept of a validity domain, which further constrains the optimization to stay close to the training data. One common choice forces the decision variable to lie within the convex hull of the data. In this talk, we propose a new validity domain, which uses the convex-hull idea in an extended space. We investigate its properties and compare it empirically with existing techniques on a set of test problems for which the ground-truth optimization problem is known. We also consider our approach within a pricing case study using real-world data. This is joint work with Yilin Zhu at the University of Iowa.

# Biographie

Sam Burer is the Tippie Rollins Professor in the Department of Business Analytics at the University of Iowa. He received his Ph.D. from Georgia Tech, and his research focuses on convex optimization. He is the recipient of the 2020 INFORMS Computing Paper Prize and the 2023 SIAM Optimization Test of Time Award. His work has been supported by grants from the National Science Foundation, including the CAREER award, and he currently serves as an area editor of Operations Research and as an associate editor for SIAM Journal on Optimization and Mathematical Programming. He also serves as Treasurer of the Mathematical Optimization Society and is a past Vice Chair of the SIAM Activity Group on Optimization. He teaches at all levels of business education, served as the founding faculty director of two Master's programs, and is the 2022 recipient of the University of Iowa's President and Provost Award for Teaching Excellence.
