---
title: "International environmental agreements in the presence of adaptation and self-image"
author: "[Lucia Sbragia](https://www.durham.ac.uk/business/our-people/lucia-sbragia/)"
date: 2024-04-30
categories: [2023-2024]
draft: false
room: "salle à déterminer"
time: "11h00"
url: https://www.durham.ac.uk/business/our-people/lucia-sbragia/
---

# Résumé

We examine the stability and effectiveness of an international environmental agreement when countries can decide both their emissions and adaptation levels. We assume that adaptation requires a prior irreversible investment and presents the characteristics of a private good by reducing a country's vulnerability to the impact of pollution, while mitigation policies produce a public good by reducing the total amount of pollution.
By using a stylized model capturing the main features of the Paris agreement, we show that investments in adaptation do not ameliorate the participation to the agreement, total emissions by countries are higher than when countries can only emit, and that global welfare is higher with adaptation than without. All this suggests that adaptation is beneficial even if there may be a loss in participation. We also investigate the impact of a regulated adaptation. This is based on joint work with Michèle Breton.

# Biographie

Dr. Lucia Sbragia est professeure agrégée de sciences économiques à l'école de gestion de l'Université Durham au Royaume-Uni. Ses intérêts de recherches portent sur l'application de concepts de théorie des jeux et de modélisation nonlinéaire dynamique pour l'étude d'enjeux en lien avec l'environnement et les ressources naturelle, notamment la pêche durable et les accords globaux pour la réduction des émissions de polluants. Elle est détentrice d'un doctorat en économie de l'*Università Cattolica del Sacro Cuore* à Milan.
