---
title: "High-dimensional approximate dynamic matrix factor models: Estimation via the Kalman smoother and the EM algorithm"
author: "[Luca Trapin](https://sites.google.com/site/lucatrapin/home)"
date: 2024-08-29
categories: [2024-2025]
draft: false
room: "salle [Paris](https://www.hec.ca/campus/cote_sainte_catherine/3e_etage/salles_cours/paris.html)"
time: "10h00"
url: https://sites.google.com/site/lucatrapin/home
---

# Résumé


High-dimensional matrix-variate time series data are becoming increasingly popular in economics and finance. This has stimulated the development of matrix factor models to achieve significant dimension reduction. This paper proposes an approximate dynamic matrix factor model that accounts for the time series nature of the data, and develops an estimator of the model parameters based on the EM algorithm and the Kalman smoother that allows to handle arbitrary patterns of missing data. We establish the consistency of the estimated loadings and factor matrices. The finite sample properties of the estimators are assessed through a large simulation study and an application to a financial dataset. This is joint work with Matteo Barigozzi (University of Bologna).

 

# Biographie

Dr. Luca Trapin is an associate professor of economic statistics in the Department of Statistics at the University of Bologna. Before moving to Bologna, he was Assistant Professor of Econometrics at Università Cattolica del Sacro Cuore, Post-doctoral Fellow in the Quantitative Finance Group at Scuola Normale Superiore in Pisa, under the supervision of Prof. Davide Pirino, and Post-doctoral Fellow at the Department of Decision Sciences at HEC Montréal, under the supervision of Prof. Debbie Dupuis. Luca received my Ph.D. in Economics from IMT School for Advanced Studies Lucca, under the supervision of Prof. Massimo Riccaboni and Prof. Marco Bee. His research interests are in statistical analysis of financial data, extreme value analysis for policy decisions, economics and business forecasting.
