---
title: "Scalable design with posterior-based operating characteristics"
author: "[Luke Hagar](https://uwaterloo.ca/scholar/lmhagar)"
date: 2024-11-22
categories: [2024-2025]
draft: false
room: "salle à déterminer"
time: "13h00"
url: https://uwaterloo.ca/scholar/lmhagar
---

# Résumé



To design trustworthy Bayesian studies, criteria for posterior-based operating characteristics --- such as power and the type I error rate --- are often defined in clinical, industrial, and corporate settings. These posterior-based operating characteristics are typically assessed by exploring sampling distributions of posterior probabilities via simulation. In this paper, we propose a scalable method to determine optimal sample sizes and decision criteria that maps posterior probabilities to low-dimensional conduits for the data. Our method leverages this mapping and large-sample theory to explore sampling distributions of posterior probabilities in a targeted manner. This targeted exploration approach prompts consistent sample size recommendations with fewer simulation repetitions than standard methods. We repurpose the posterior probabilities computed in that approach to efficiently investigate various sample sizes and decision criteria using contour plots.

# Biographie

Dr. Luke Hagar is a postdoctoral fellow at McGill University. He obtained a PhD degree in statistics in 2024 from Waterloo, completed under the supervision of Nathaniel Stevens. Luke works in the field of experimental design: his research interests revolve around  efficient sampling techniques, hypothesis testing, Bayesian methods, and computational inference.
