---
title: "Evaluating a major home energy efficiency retrofit program"
author: "[Nicholas Rivers](https://sites.google.com/site/nicholasjrivers/)"
date: 2024-04-05
categories: [2023-2024]
draft: false
room: "salle à déterminer"
time: "11h00"
url: https://sites.google.com/site/nicholasjrivers/
---

# Résumé

We quantify realized energy consumption, bill savings, and rebates disbursed from Canada's energy efficiency retrofit program. We find that retrofits reduce natural gas consumption for up to 10 years in the average participating home by about 21%, representing 61% of model-predicted natural gas savings. Whole-envelope retrofits are predicted to reduce natural gas consumption by 67%, but in practice only half of these savings are realized. Electricity consumption did not appreciably change, and several recommended retrofits save zero energy. Program-induced gas bill savings peak among relatively low wealth households, whereas rebates were disbursed equally across the house wealth distribution. This is joint work with Maya Papineau and Kareman Yassin.

# Biographie


Nicholas Rivers is Associate Professor at the Graduate School of Public and International Affairs and the Institute of the Environment at the University of Ottawa.  His research focuses on the economic evaluation of environmental policies, using econometric and computational methods. He has received awards and grants for his research from the Trudeau Foundation, the Social Science and Humanities Research Council, and the National Science and Engineering Research Council. He serves as an expert panel member for the Canadian Climate Institute and as the Director for graduate programs at the Institute of the Environment. From 2011-2021, he was Canada Research Chair in Climate and Energy Policy.  From 2016-2022 he was a co-editor of the Journal of Environmental Economics and Management.
