---
title: "Skew-symmetric approximations of posterior distributions"
author: "[Daniele Durante](https://danieledurante.github.io/web/)"
date: 2024-03-15
categories: [2023-2024, CMSQ]
draft: false
room: "Zoom"
time: "11h00"
url: https://danieledurante.github.io/web/
---

# Résumé



A broad class of regression models that routinely appear in several fields of application can be expressed as partially or fully discretized Gaussian linear regressions. Besides incorporating the classical Gaussian response setting, this class crucially encompasses probit, multinomial probit and tobit models, among others. The relevance of these representations has motivated decades of active research within the Bayesian field. A main reason for this constant interest is that, unlike for the Gaussian response setting, the posterior distributions induced by these models do not seem to belong to a known and tractable class, under the commonly-assumed Gaussian priors. In this seminar, I will review, unify and extend recent advances in Bayesian inference and computation for such a class of models, proving that unified skew-normal (SUN) distributions (which include Gaussians as a special case) are conjugate to the general form of the likelihood induced by these formulations. This result opens new avenues for improved sampling-based methods and more accurate and scalable deterministic approximations from variational Bayes. These results are further extended via a general and provably-optimal strategy to improve, via a simple perturbation, the accuracy of any symmetric approximation of a generic posterior distribution. Crucially, such a novel perturbation is derived without additional optimization steps and yields a similarly-tractable approximation within the class of skew-symmetric densities that provably enhances the finite-sample accuracy of the original symmetric approximation. Theoretical support is provided, in asymptotic settings, via a refined version of the Bernstein–von Mises theorem that relies on skew-symmetric limiting densities.

# Biographie

Dr. Daniele Durante est professeur adjoint à l'Université Bocconi depuis 2017 et chercheur affilié à l'institut de sciences des données et d'analytique de Bocconi, du centre DONDENA de recherche en dynamique sociale et politique publique et du Laboratoire de recherche sur la crise du coronavirus. Daniele a obtenu son doctorat sous la direction de Bruno Scarpa, co-encadré par David Dunson, à l'Université de Padoue, où ila également complété sa maîtrise et un stage post-doctoral. Il est éditeur associé de Biometrika, du *Journal of Computational and Graphical Statistics* et du *Journal of Multivariate Analysis*.
Durante travaille sur la recherche disciplinaire et la méthodologie bayésienne; il est le récipiendaire de nombreux prix, dont le prix Laplace, le prix Mitchell, et le prix de la meilleure thèse de doctorat de la *Società Italiana di Statistica*.
