---
title: "A Dynamic Equilibrium Model of Liquidity Risk"
author: "[Xiaofei Shi](https://xf-shi.github.io/)"
date: 2025-03-10
categories: [2024-2025, Quantact]
draft: false
room: "salle [Associations étudiantes](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/associations-etudiantes.html)"
time: "13:30"
url: https://xf-shi.github.io/
---

# Résumé


We present a framework for analyzing the equilibrium implications of liquidity risk dynamics on asset prices. Our model features two risk-averse agents who continuously trade a security to hedge nontraded risks, while facing stochastic transaction costs correlated with their trading needs. We derive explicit solutions for equilibrium prices and traded quantities under small transaction costs, showing that the illiquidity discount increases with the correlation between trading costs and trading needs. Calibrating the model using NYSE and AMEX data, we find that liquid portfolios recover faster from liquidity shocks and exhibit smaller fluctuations, whereas illiquid portfolios are highly sensitive to trading-cost dynamics. For the most illiquid portfolio, the illiquidity discount increases by 12.75% with full correlation comparing to the uncorrelated case.


# Biographie

Dr. Xiaofei Shi is an assistant professor in the Department of Statistical Sciences at the University of Toronto. Before joining UofT, she worked as a Term Assistant Professor at Columbia University. Xiaofei obtained a PhD in Mathematical Finance at Carnegie Mellon University, under the supervision of Prof. Johannes Muhle-Karbe. Her research interests revolve around  stochastic optimization and stochastic differential equations with applications to mathematical finance.
