---
title: "A Generalized Logrank-type Test for Comparison of Treatment Regimes in Sequential Multiple Assignment Randomized Trials"
author: "[Marie Davidian](https://statistics.sciences.ncsu.edu/people/davidian/)"
date: 2025-01-24
categories: [CSMQ,2024-2025]
draft: false
room: "Zoom"
time: "15h30"
url: https://statistics.sciences.ncsu.edu/people/davidian/
---

# Résumé



The sequential multiple assignment randomized trial (SMART) is the gold standard study design for the evaluation of multistage treatment regimes, which comprise sequential decision rules that recommend treatments for a patient at each of a series of decision points based on their evolving characteristics. A common goal is to compare the set of so-called embedded regimes represented in the design on the basis of a primary outcome of interest. In the study of chronic diseases and disorders, this outcome is often a time to an event, and a goal is to compare the distributions of the time-to-event outcome associated with each regime in the set. We present a general statistical framework in which we develop a logrank-type test for comparison of the survival distributions associated with regimes within a specified set based on the data from a SMART with an arbitrary number of stages that allows incorporation of covariate information to enhance efficiency and can also be used with data from an observational study. The framework provides clarification of the assumptions required to yield a principled test procedure, and the proposed test subsumes or offers an improved alternative to existing methods. The methods are applied to a SMART in patients with acute promyelocytic leukemia. This is joint work with Anastasios A. Tsiatis.

 

# Biographie

Dr. Marie Davidian is the J. Stuart Hunter Distinguished Professor at the Department of Statistics of North Carolina State University in Raleigh. She received her Ph.D. in Statistics from the Department of Statistics at the University of North Carolina at Chapel Hill in 1987 under the direction of Raymond J. Carroll. Her interests include statistical methods for estimating optimal treatment regimes from data; methods for analysis of clinical trials and observational studies, including approaches for drawing causal inferences; statistical models and methods for analysis of longitudinal data, especially nonlinear mixed effects models; methods for handling missing and mismeasured data; and pharmacokinetic and pharmacodynamic analysis. She is a former president of ENAR' COPS, a fellow of IMS, ASA, AAAS. Marie has published four books, more than 135 research papers. She has advised or co-supervised more than 30 PhD students and is recognized worldwide for her service to the profession and her expertise.
