---
title: "Environmental Policy under Risk Aversion: Prices vs. Quantities"
author: "[Afzal Siddiqui](https://www.hec.ca/profs/afzal.siddiqui.html)"
date: 2025-10-22
categories: [2025-2026]
draft: false
room: "salle [Esdras-Minville](https://www.hec.ca/campus/cote_sainte_catherine/4e_etage/salles/esdras-minville.html)"
time: "13h30"
url:  https://energie.hec.ca/events/environmentalpolicyunderriskaversionpvsq/
---

# Résumé

Mechanisms to regulate to regulate environmental externalities can be divided into price and quantity instruments, e.g., taxes and caps, respectively. Absent uncertainty in the cost and benefit of abatement, these instruments yield equivalent results. However, given uncertainty, Weitzman (1974) proved that the expected loss in social welfare vis-à-vis the optimal policy could diverge based on the choice of instrument. While the literature has extended the analysis to cover features such as multiple pollutants and market power by producers, the impact of risk aversion has not yet been considered. Taking the perspective of a risk-averse regulator that anticipates the behaviour of a perfectly competitive industry that produces an externality, we tackle analytically how optimal price (P) or quantity (Q) regulation is affected by the regulator’s degree of risk aversion. We use a bi-level mean-variance framework for analysis. At the lower level, a perfectly competitive industry reacts to uncertainty in inverse demand, or the marginal benefit (MB) of consumption, while its marginal cost (MC) is deterministic. Scenario-specific industry production maximises profit inclusive of the restriction of any environmental control imposed by the regulator. At the upper level, a risk-averse regulator selects the level of the environmental control, i.e., either a tax or a cap on externalities, in anticipation of industry’s response. In terms of the Q instrument, we note that a cap fixes industry output but obviates its ability to respond to the MB’s variations. Thus, greater risk aversion straightforwardly decreases the optimal cap in terms of the MB and MC. Intuitively, a ceteris paribus increase in the cap leads to more exposure to uncertainty in the realised welfare in the form of higher gross consumer surplus, thereby incentivising the regulator to lower the cap with risk aversion. By contrast, for a P instrument, the imposition of a tax shifts the MC of production while still allowing the output to adjust to the uncertainty in the MB of consumption. Consequently, it has the seemingly counterintuitive result of decreasing the optimal tax, i.e., actually inducing an increase in expected production, with risk aversion. In effect, increasing the tax could make the gains in welfare due to avoided damage costs more vulnerable to random demand shocks, thereby necessitating a lower production tax for ceteris paribus increases in risk aversion.

# Biographie

He is a Professor in the Department of Computer and Systems Sciences at Stockholm University and an Adjunct Professor in the Department of Mathematics and Systems Analysis at Aalto University. Previously, he was Professor of Energy Economics in the Department of Statistical Science at University College London and a Visiting Professor in the Department of Decision Sciences at HEC Montréal. His research interests are in the application of operational research methods to analyse decision making under uncertainty and competition in the energy sector. Besides participation in and coordination of several research projects, he has also served as a consultant to the Energy Technologies Area of the Ernest Orlando Lawrence Berkeley National Laboratory and the Directorate‑General for Communications Networks, Content and Technology (DG CONNECT) of the European Commission.