---
title: "Optimizing Mobility and Fairness in Public Housing Allocation"
author: "[Yichuan Daniel Ding](https://www.mcgill.ca/desautels/yichuan-daniel-ding)"
date: 2025-11-26
categories: [2025-2026]
draft: false
room: "salle [Port-au-Prince](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/port-au-prince.html)"
time: "11h00"
url:  
---

# Résumé

We study a centralized public housing allocation problem, where a housing authority, faced with both move-in and transfer requests, is tasked with the assignment of available housing units to applicants. Motivated by operational challenges at a Canadian provincial housing authority (hereafter, the Housing Authority), we propose a dynamic allocation framework whose objective function incorporates both mobility and fairness. We model the unmet requests from one housing type i to type j as a queue indexed by (i,j), and adapt the dynamic matching queue framework developed by Gurvich and Ward (2014) to analyzing this problem, where each matching corresponds to a circulation over the directed graph. We propose a periodic review policy, in which the optimal housing allocation is derived from solving a min-cost circulation problem with convex costs. We prove that by selecting the appropriate review cycle, the periodic review policy is asymptotically optimal as arrival rates grow large, converging to an imbalance-based lower bound  at an improved rate compared to Gurvich and Ward (2014). In a case study, we use real data to simulate the public housing waitlist system, evaluate the trade-off between fairness and mobility, and demonstrate near optimality of our policy.

# Biographie

Yichuan Ding is an Associate Professor at the Desautels Faculty of Management, McGill University, where he holds the title of Desautels Faculty Scholar and serves as the Academic Director of the Global Manufacturing and Supply Chain Management (GMSCM) Master's Program. He earned his Ph.D. in Management Science and Engineering from Stanford University in 2012. Dr. Ding's research focuses on applying operations research and Artificial Intelligence to enhance the efficiency and equity of healthcare delivery systems. His research has been published in leading journals such as Operations Research, Mathematics of Operations Research, Manufacturing & Service Operations Management (M&SOM), and Production and Operations Management (POM). His work has been recognized with several honors, including winning the 2023 POMS College of Healthcare Operations Management Best Paper Competition and being named a finalist for the 2019 Pierskalla Best Paper Competition and the 2017 INFORMS Behavioral Operations Management Best Working Paper Competition. Dr. Ding currently serves as an Associate Editor for M&SOM, Service Science, and Operations Research Letters. He co-chaired the 2023 INFORMS MSOM Conference in Montreal. Dr. Ding currently serves as the chair of INFORMS MSOM/Healthcare SIG and the Vice President/President-Elect of the CORS Health Care Operational Research SIG. He served as the President of the Canadian Operational Research Society (CORS) Queueing and Applied Probability SIG from 2022 to 2024.