---
title: "tests Forced LiquidatioRobinhood’ns"
author: "[Diego Amaya](https://www.wlu.ca/academics/faculties/lazaridis-school-of-business-and-economics/faculty-profiles/diego-amaya/index.html)"
date: 2025-11-28
categories: [2025-2026]
draft: false
room: "TBD"
time: "14h00"
url:  https://energie.hec.ca/events/environmentalpolicyunderriskaversionpvsq/
---

# Résumé

We exploit Robinhood’s forced liquidations to identify retail option trades. Intraday volume-spikes line up exactly with Robinhood’s policy and shift when the policy changes; a SPY–SPX placebo confirms that Robinhood access is the underlying driver. We document that sell orders of calls largely representing the forced closure of call positions previously bought by retail investors- dominate, complex orders are prevalent, and that trading popularity is divided between mega-caps and meme-style names. Execution costs are substantial: spreads widen, and market makers capture profits. Forced liquidations spill over into equities, with delta-hedging flows moving underlying stock returns.

# Biographie

Diego Amaya is an Associate Professor of Finance and the Goldberg Family Foundation Fellow at Wilfrid Laurier University. He earned a master’s and PhD in Financial Engineering from HEC Montréal. He joined Laurier in 2016. His research interests include empirical asset pricing, credit risk, derivatives, option pricing, high-frequency price analysis, and risk management.