---
title: "Placebo Tests Done Right"
author: "[Guillaume A. Pouliot](https://sites.google.com/site/guillaumeallairepouliot/)"
date: 2025-01-16
categories: [2024-2025]
draft: false
room: "salle [Hélène-Desmarais](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/hdesmarais.html)"
time: "11h00"
url: https://sites.google.com/site/guillaumeallairepouliot/
---

# Résumé


In order to assess the significance of a regressor, applied regression analysts sometimes rerun their regression replacing the regressor of interest with a randomly perturbed --- often permuted --- version which is expected to be insignificant, i.e., a placebo. While these procedures are often heuristic in their justification, p -values are often reported. We observe that the interpretation of such placebo tests --- for observational data --- as Fisher test –designed for experimental data– is common bu misleading, and that many such placebo tests and p-values are in fact invalid. In particular, we argue that almost all such tests for multivariate linear regression are invalid. A unified treatment of randomization inference and Fisher tests suggests more robust interpretations and designs of such placebo procedures, and allows us to handle the multivariate linear regression case.  We will spend the main part of the presentation producing such a valid test for observational data.


# Biographie

Dr. Guillaume A. Pouliot is assistant professor at the Harris School of Public Policy and the College at the University of Chicago. Pouliot received his PhD from Harvard University.  Previously, he received his B.A. (Honors) in economics as well as his M.S. (concurrent) in statistics from the University of Chicago. His current research focuses on developing statistical methods for nonstandard problems in public policy and economics, as well as the extension of machine learning methods for applications in public policy, and problems at the interface of econometrics and optimization. 
