---
title: "TBA"
author: "[Aurélien Nicosia](https://www.linkedin.com/in/aur%C3%A9lien-nicosia-6a52487b/?originalSubdomain=ca)"
date: 2026-01-28
categories: [2025-2026]
draft: false
room: "TBD"
time: "13h30"
url:  https://www.linkedin.com/in/aur%C3%A9lien-nicosia-6a52487b/?originalSubdomain=ca
---

# Résumé

Cette conférence présentera comment l’intelligence artificielle transforme simultanément le soutien académique, l’enseignement universitaire et la recherche en statistiques et en science des données. Elle abordera notamment le développement de GPT-CDA, un tuteur virtuel offrant un accompagnement personnalisé en mathématiques et en statistiques, ainsi que l’intégration des modèles de langage dans les activités pédagogiques pour enrichir l’analyse, l’interprétation et les projets étudiants. La présentation montrera aussi comment l’IA accélère le développement méthodologique et optimise les workflows de recherche, tout en soulevant les enjeux de validation, de reproductibilité et d’intégrité scientifique. Une occasion de découvrir des usages concrets et actuels de l’IA dans le milieu universitaire.


# Biographie

Après l’obtention de son doctorat en statistique à l’Université Laval, Aurélien Nicosia a travaillé plusieurs années dans le secteur privé, notamment chez GSK comme manager en science des données, puis chez Co-operators comme directeur de la recherche et de l’innovation analytique, où il était responsable de projets en intelligence artificielle appliquée et chargé des partenariats académiques avec plusieurs universités au Québec.Il est aujourd’hui chargé d’enseignement et responsable du Centre de dépannage et d’apprentissage (CDA) au département de mathématiques et de statistique de l’Université Laval. Il y contribue à l’intégration d’outils d’intelligence artificielle en soutien à l’apprentissage, notamment avec le développement du GPT-CDA. Parallèlement, il poursuit ses travaux de recherche en statistique et explore l’usage de l’IA dans ses démarches de recherche, tout en participant à la conception des cours du nouveau baccalauréat en sciences des données.