project:
  type: website
  output-dir: docs
  
website:
  title: "Séminaires de sciences de la décision"
  navbar:
    pinned: true
    background: "#003C71"
    right:
      - archives.qmd
  search: 
    location: navbar
    type: textbox

  page-footer:
    left: |
      [Département de sciences de la décision](https://www.hec.ca/mqg/), [HEC Montréal](www.hec.ca)
    right: |
      Fabriqué avec [Quarto](https://quarto.org/)
format:
  html:
    theme:
      - litera
      - html/custom.scss
  
lang: fr
date-format: "ddd, D MMM YYYY"
