---
title: "Optimal picking policies for e-commerce warehouses"
author: "[Maximilian Schiffer](https://www.professoren.tum.de/en/schiffer-maximilian/)"
date: 2019-09-10
url: https://www.professoren.tum.de/en/schiffer-maximilian/
categories: ["2019-2020", "GERAD"]
---


# Résumé

In e-commerce warehouses, online retailers increase their efficiency by using a mixed-shelves (or scattered storage) concept, where unit loads are purposefully broken down into single items, which are individually stored in multiple locations. Irrespective of the stock keeping units a customer jointly orders, this storage strategy increases the likelihood that somewhere in the warehouse the items of the requested stock keeping units will be in close vicinity, which may significantly reduce an order picker's unproductive walking time. In this talk, we optimize picker routing through such mixed-shelves warehouses. Specifically, we introduce a generic exact algorithmic framework that covers a multitude of picking policies, independently of the underlying picking zone layout, and is suitable for real-time applications. This framework embeds a bidirectional layered graph algorithm which provides the best known performance for the simple picking problem with a single depot and no further attributes. We compare three different real-world e-commerce warehouse settings that differ slightly in their application of scattered storage and in their picking policies. Based on these, we derive additional layouts and settings that yield further managerial insights. Our results reveal that the right combination of drop-off points, dynamic batching, the utilization of picking carts, and the picking zone layout can greatly improve the picking performance. In particular, some combinations of policies yield efficiency increases of more than 20%.

# Biographie

Maximilian Schiffer is an Assistant Professor of Operations and Supply Chain Management at TUM School of Management, Technical University of Munich. Before joining TU Munich, he was a Visiting Postdoctoral Scholar at Stanford University and a Postdoctoral Scholar at RWTH Aachen University. Dr. Schiffer is an Associate Member of the GERAD. He received a Ph.D. degree in Operations Research from RWTH Aachen University in 2017. Dr. Schiffer's expertise lies in in the field of Operations Research and Management Science, specifically in Dynamic Programming, (Mixed) Integer Programming, Metaheuristics, Exacts, Robust Optimization, Machine Learning, and Forecasting, applied to a variety of complex application fields, e.g., Transportation Problems, Supply Chains, Production Networks, and Big Data. His research on electric vehicles and logistics networks with intermediate stops has been awarded with numerous prizes, e.g., the INFORMS TSL Dissertation Prize and the GOR Doctoral Dissertation Prize.
