---
title: "Life at the (grid edge): Evaluating energy decentralization strategies in California"
author: "[Ahmed Abdulla](http://ayabdulla.com)"
date: 2019-11-29
categories: ["2019-2020"]
heure: "11h00"
---


# Résumé

Avoiding the worst consequences of climate change hinges on the transition to a deeply decarbonized global energy system. Recent studies suggest that the least costly and risky way in which this transition could unfold is through radical electrification that is dominated by low-carbon sources of electricity. Several visions of this future have been put forward, some of which hinge on revolutions at the grid-edge that enable smarter energy management and vehicle electrification.

This talk will cover recent and ongoing research on the next wave of technical and policy interventions at the grid-edge that have the potential to transform the electric power system. In California, policy makers are promoting distributed energy resources like residential solar and energy storage and expecting that they will both decarbonize and decentralize the electric power system. This presentation will describe a systematic analysis of the unintended effects of deploying residential energy storage (RES) systems. Our results show that RES systems predominantly increase emissions when users seek to minimize their electricity cost.

Another development at the grid-edge is the proliferation of electric vehicles (EV). California’s size and status as an early adopter of regulatory standards has given it influence in establishing trends which the rest of the nation inherits. The role it plays in efforts to decarbonize transportation could prove revelatory: the state accounts for 10% of new vehicle sales and 50% of EV sales in the U.S. However, one obstacle to policy development is the dearth of information about EV adopters' attitudes towards incentives, charging, and potentially emergent challenges. This talk will present preliminary results from a large survey of EV adopters in Southern California that reveals these attitudes and allows modelers and policy makers to elaborate strategies for managing a grid with high EV penetration.


# Biographie

Ahmed Abdulla is Assistant Research Professor in the Department of Engineering and Public Policy at Carnegie Mellon University, 
and a Research Fellow in the Deep Decarbonization Initiative at the University of California, San Diego. His research uses large, 
empirical data, optimization and decision analysis to model the strategic development and deployment of innovative energy technologies 
that decarbonize the energy system and increase its resiliency. His work has been supported by the U.S. National Science Foundation, 
the Alfred P. Sloan Foundation and the John D. and Catherine T. MacArthur Foundation, among others. Results from his research have been 
published in leading journals, including Nature Climate Change and the Proceedings of the National Academy of Sciences; they have also 
been featured in the Wall Street Journal, Bloomberg News and The Los Angeles Times. Prior to Carnegie Mellon, Abdulla was an Assistant 
Research Scientist in the Center for Energy Research at the University of California, San Diego. He holds a PhD in Engineering and 
Public Policy from Carnegie Mellon University (2014) and a BS in Chemical Engineering from Princeton University (2009). 
