---
title: "Risk-neutral moments based estimation of continuous time jump-diffusion models"
author: "[Bruno Feunou](https://sites.google.com/view/bruno-feunou/home)"
url: 
date: 2020-12-04
categories: ["2020-2021", Zoom]
---

# Résumé

This paper provides a novel methodology for estimating option pricing models based on risk‐neutral moments. We synthesize the distribution extracted from a panel of option prices and exploit linear relationships between risk‐neutral cumulants and latent factors within the continuous time affine stochastic volatility framework. We find that fitting the Andersen *et al.* (Journal of Financial Economics, 2015, 117(3), 558–584) option valuation model to risk‐neutral moments captures the bulk of the information in option prices. Our estimation strategy is effective, easy to implement, and robust, as it allows for a direct linear filtering of the latent factors and a quasi‐maximum likelihood estimation of model parameters. From a practical perspective, employing risk‐neutral moments instead of option prices also helps circumvent several sources of numerical errors and substantially lessens the computational burden inherent in working with a large panel of option contracts.

# Biographie

Bruno Feunou is a Research Advisor at the Bank of Canada’s Financial Markets Department. Before this position at the Bank of Canada, he worked at Duke University as a post-doc associate. He completed his Ph.D degree at the University of Montreal. Bruno Feunou research interest are option and bond pricing, the linkages between term structure of interest rate and the macroeconomy.
