---
title: "Banking networks, systemic risk, and the credit cycle in emerging markets"
author: "[Madhu Kalimipalli](https://www.madhukalimipalli.com/)"
date: 2020-10-23
categories: [2020-2021, Zoom]
url: https://www.madhukalimipalli.com/
---


# Résumé

We undertake a large-scale empirical examination of systemic risk among 1048 financial institutions in a large sample of 23 emerging markets, broken down into 5 regions. This work extends the large literature on systemic risk in the US, Europe, and other developed countries to emerging markets, which is relatively under-researched. We present a novel systemic risk score for each financial system by region, across time. This measure is additively decomposable and attributable to each financial institution, and may be used as an objective and quantifiable measure of whether a bank is a SIFI (systemically important financial institution). The level and timing of systemic risk is heterogenous across the 5 regions, and this risk is concentrated in a few banks, more so pre-crisis than post-crisis. Credit and network effects account for over 2/3 of systemic risk (and in some cases, almost all of the risk), and the remaining comes from individual bank variables. Spillovers of systemic risks across regions are mostly contemporaneous within the quarter. A primary principal component (default level) accounts for 1/2 of the variation in systemic risk across the regions with the next two principal components (policy uncertainty and liquidity) accounting for 1/5 each. Aggregate default risk in a region is statistically predictable using our systemic risk metric, thereby supporting timely macro-prudential policy-making.


# Biographie

Madhu Kalimipalli is an Equitable Life of Canada Fellow and Full Professor in Finance at the Lazaridis School of Business and Economics, Wilfrid Laurier University, Waterloo, Canada, and the Director of PhD and Research-based Master’s Programs in Management. Prior to joining Laurier in 2000, he was a visiting Assistant professor at the Faculty of Management in McGill University. He holds a PhD in Finance from the Bauer College of Business, University of Houston, and MA degrees in Economics from Rutgers University and the Gokhale Institute of Politics and Economics, Pune, India. His research has appeared in premier finance journals such as Journal of Financial Economics, Journal of Financial Intermediation, Journal of Banking and Finance, Journal of Empirical Finance, among others.
