---
title: "Longitudinal functional regression: tests of significance"
author: "[Ana-Maria Staicu](https://www4.stat.ncsu.edu/~staicu/)"
date: 2020-01-31
url: https://www4.stat.ncsu.edu/~staicu/
categories: ["2019-2020","Statlab"]
heure: "16h00"
---


## Résumé:

We consider longitudinal functional regression, where, for each subject, the response consists of multiple curves observed at different time visits. We discuss tests of significance in two general settings. First, when there are no additional covariates, we develop a hypothesis testing methodology for formally assessing that the mean function does not vary over time. Second, in the presence of other covariates, we propose a testing procedure to determine the significance of the covariate's time-varying effect formally. The methods account for the complex dependence structure of the response and are computationally efficient. Numerical studies confirm that the testing approaches have the correct size and are have a superior power relative to available competitors. We illustrate the methods on a real data application.


## Biographie de la conférencière:

Ana-Maria Staicu is Associate Professor in the Department of Statistics, North Carolina State University. She completed a PhD in 2007 from University of Toronto CA, under the supervision of Nancy Reid. Before joining NC State in 2009, she was a Brunel research fellow at the University of Bristol UK and also worked with Ciprian Crainiceanu and Ray Carroll. Her research interests are primarily in functional data analysis, longitudinal data analysis, nonparametric statistics, and brain imaging analysis. It has been applied to brain tractography studies of MS and brain imaging studies more general, wearable computing, animal studies, and environmental studies. She is a recipient of the NSF Career Award. 
