---
title: "Optimizing Post-Disruption Response Operations to Improve Resilience of Critical Infrastructure Systems"
author: "[Ozlem Ergun](https://coe.northeastern.edu/people/ergun-ozlem/)"
date: 2020-10-16
categories: ["2020-2021",Zoom]
url: https://coe.northeastern.edu/people/ergun-ozlem/
---

# Résumé

Critical infrastructure systems (CIS) underpin almost every aspect of the modern society by enabling the essential functions through overlaying service networks. After a disruption impacting the CIS, the functionality of the overlaying service networks degrades. Thus, after an extreme event, in order to minimize the negative impact to society, it is crucial to restore the disrupted CIS as soon as possible. In this talk, we focus on disruptions created by natural hazards on transportation CIS and develop methods to efficiently plan the post-disaster response operations. 
In the aftermath of a natural disaster, the transportation network is disrupted due to the debris blocking the roads and obstructing the flow of relief aid and search-and-rescue teams between critical facilities and disaster sites. In the first few days following a disaster, in order to deliver aid to those in need, blocked roads must be cleared by pushing the debris to the sides. In this context, we define the road network recovery problem (RNRP) as finding a schedule to clear the roads with limited resources such that all the service demanding locations are served in the shortest possible time. First, we address the deterministic RNRP and propose a novel network science inspired measure to quantify the criticality of the components within a disrupted service network and develop a restoration heuristic. Next, we consider RNRP with stochastic demand and propose an approximate dynamic programming approach for identifying an effective policy under uncertainty.


# Biographie

Dr. Özlem Ergun is a professor in Mechanical and Industrial Engineering at Northeastern University. Dr. Ergun’s research focuses on design and management of large-scale and decentralized networks. She has applied her work on network design, management, and resilience to problems arising in many critical systems including transportation, pharmaceuticals, and healthcare.  She has worked with organizations that respond to emergencies and humanitarian crises around the world, including USAID, UNWFP, UNHCR, IFRC, OXFAM America, CARE USA, FEMA, USACE, CDC, AFCEMA, and MedShare International. Dr. Ergun is currently serving as a member of the National Academies Committee on Building Adaptable and Resilient Supply Chains after Hurricanes Harvey, Irma, and Maria. Within INFORMS, Dr. Ergun has been a leader in establishing a strong community of OR/MS professionals with an interest in public programs.  She was the President of INFORMS Section on Public Programs, Service and Needs in 2013. She currently serves as the Area Editor at the Operations Research journal for Policy Modeling and the Public Sector Area. Dr. Ergun is also a founding co-chair of the annual Health and Humanitarian Logistics Conference, held annually since 2009. In addition, Dr. Ergun was the Vice President of Membership and Professional Recognition on the INFORMS Board of Directors, 2011 - 2015.  Prior to joining Northeastern she was the Coca-Cola Associate Professor in the School of Industrial and Systems Engineering at Georgia Institute of Technology, where she also co-founded and co-directed the Health and Humanitarian Systems Research Center at the Supply Chain and Logistics Institute.  She received a B.S. in Operations Research and Industrial Engineering from Cornell University in 1996 and a Ph.D. in Operations Research from the Massachusetts Institute of Technology in 2001.
