---
title: "Rethinking Introductory Statistics for Life Sciences Programs"
author: "[Bethany White](https://www.statistics.utoronto.ca/people/directories/all-faculty/bethany-white), [Jastaranpreet Singh](https://www.immunology.utoronto.ca/faculty/jasty-singh)"
url: ["https://www.statistics.utoronto.ca/people/directories/all-faculty/bethany-white","https://www.immunology.utoronto.ca/faculty/jasty-singh"]
date: 2021-05-18
categories: ["2020-2021","McGill biostat","Zoom"]
heure: "13h30"
---

# Résumé

Despite reproducibility concerns in science, an increased awareness of the prevalence of statistical errors in life sciences research, and even a tightening up of quantitative reporting standards in journals, statistical errors continue to permeate life sciences research. Yet, life science students often only need to take one Statistics course in their undergraduate programs, if that. What can we, as educators, do to prepare future life scientists for statistical practice in research when we have such limited time with them?   
  
In a collaboration between the Department of Statistical Sciences and the Human Biology Program at the University of Toronto, a second-year undergraduate course was introduced a few years ago to integrate statistics instruction with research design to improve the quantitative training of life sciences students. A study was conducted in this course to explore students’ perceptions about statistical practice in the life sciences and their preparedness use statistical methods appropriately in research. Student attitudes and self-efficacies for Statistics, as well as their abilities to recognize and handle problems related to statistical practice in life sciences research was assessed by way of surveys administered at the beginning and end of the course. In this talk, we will highlight this course, share key findings of the study, and reflect on how the results can help inform future course offerings and training initiatives to better prepare our students to effectively engage with Statistics in research.  

# Biographie

Dr. Bethany White holds a BScH in Mathematics and Statistics from Acadia University and a PhD in Statistics/Biostatistics and a M.Math in Statistics, both from the University of Waterloo. She is the Associate Chair for Undergraduate Studies in Statistics and an Associate Professor, Teaching Stream, in the Department of Statistical Sciences at the University of Toronto. Her research interests involve the impact of technology-enhanced and simulation activities on student learning and attitudes toward statistics. She also has a pedagogical interest in the quantitative training of life sciences students. She served on the Statistical Society of Canada (SSC) Statistical Education Section Executive Committee between 2013-2016 (President of the Section for 2014-2015) and is currently on the SSC Board of Directors, and has served on the editorial boards of a couple of statistics education journals and on organizing committees for statistics and science education workshops and conferences in Canada and the US.

Dr. Jasty Singh received her PhD in Immunology from the University of Toronto, where she studied approaches to make immune cells from stem cells. Her postdoctoral fellowship (Institute of Biomaterials and Biomedical Engineering, University of Toronto) enabled her to extend these interests into the stem cell bioengineering space, where she engineered immune cells and developed clinically relevant biomaterials for use in immunotherapy. Currently, Jasty is an Assistant Professor, Teaching Stream with the Department of Immunology at the University of Toronto. Her previous research experiences have guided her pedagogical interests, which, in part, focus on preparing undergraduate/graduate life sciences researchers to engage with statistics in research.
