---
title: "Asymptotic Expansion Formulas for Diffusion Processes Based on the Perturbation Method"
author: "[Emanuele Guidotti](https://guidotti.dev/)"
date: 2021-01-22
url: https://guidotti.dev/
categories: [2020-2021, Zoom, "Quantact"]
heure: "11h00"
---


#### Date: 22 janvier 2021
#### Heure: 11h00-12h00



## Résumé:

Diffusion processes are a class of models that plays a prominent role in describing the time-continuous  evolution of phenomena in the natural and social sciences. However, only in very few cases the stochastic differential equation driving the process can be analytically solved. Based on the perturbation method, we present asymptotic expansion formulas to generate accurate approximations to the solution of arbitrary diffusions. In particular, we expand the characteristic function of the process. Then, the approximated expectation and moments are computed by differentiation, and the approximated transition density is written in terms of Hermite polynomials by applying Fourier transform. The computational efficiency, accuracy, and flexibility of the method are assessed via experiments conducted against closed-form solutions and Monte Carlo simulations in tasks involving density approximation, expectations, moments, filtering, and functionals of generic diffusion processes.


## Biographie du conférencier:

Emanuele Guidotti est doctorant en finance à l'Université de Neuchâtel spécialisé dans la tarification empirique des actifs. Il est également chercheur associé au CREST, Japan Science and Technology Agency depuis 2017 au sein du projet YUIMA, une équipe internationale de recherche qui oeuvre à développer un environnement complet pour l'estimation et la simulation d'équations différentielles stochastiques. Il est également partenaire au sein de Algo Finance Sagl, une jeune pousse spécialisé dans la création de logiciels et d'algorithmes en finance pour le secteur de la gestion d'actifs. Emanuele enseigne à titre de professeur associé à l'Université de Milan au sein du programme de maîtrise en science des données et économie. Emanuele détient une licence en physique et une maîtrise en économie et en finance quantitive, toutes deux décernées par l'Université de Milan cum laude.
