---
title: "Toward social welfare and fairness in kidney exchange programs"
author: "[Margarida Carvalho](http://margaridacarvalho.org/)"
date: 2022-04-28
categories: ["Chaire de théorie des jeux et gestion","2021-2022"]
url: http://margaridacarvalho.org/
heure: "11h00"
---

# Résumé

Matching markets are part of our daily lives, appearing on online platforms, school admissions and health systems. Their study attracts the interest of optimizers and game theorists. In this talk, we will focus on a particular matching market, the kidney exchange program (KEP), where combinatorial optimization and game theory play an important role.

A patient in need of a kidney transplant who has an incompatible donor can register on a KEP. The program seeks compatible donor exchanges between these patient-donor pairs to maximize patient benefit. KEPs resulting from the combination of patient-donor pools from different agents (which can be transplant centers, regions or countries) are currently being formed, requiring a game theoretical analysis. In this talk, we will recall literature on multi-player KEPs and see the extension of graph theoretical results to this game. Then, through computational experiments inspired by the Canadian KEP, we will investigate the social welfare generated by a non-cooperative multi-player KEP. These experiments will reveal the multiplicity of socially optimal solutions, leading to a new research question regarding individual patient fairness: Given multiple socially optimal matching plans, how should we select among them? We will end this talk with a proposition to tackle this question as well as an optimization methodology to efficiently implement it in practice.

# Biographie

Dr. Margarida Carvalho est une mathématicienne portugaise spécialisée dans la programmation entière mixte, la théorie des jeux algorithmique et la complexité calculatoire. Elle est professeure adjointe au Département d'informatique et de recherche opérationnelle de l'Université de Montréal depuis 2018 et est détentrice de la chaire de recherche FRQ-IVADO en science des données pour la théorie des jeux combinatoires. Margarida Carvalho est détentrice d'un doctorat en sciences informatiques, pour lequel elle a obtenu le prix EURO Doctoral Dissertation Award 2018. Elle a effectué un stage postdoctoral au sein de la Chaire d'excellence en recherche du Canada sur la science des données pour la prise de décision en temps réel suite à ses études avant d'être embauchée à l'UdeM. Margarida est actuellement rédactrice adjointe des revues INFORMS Journal on Computing, OR Spectrum et Dynamic Games and Applications.
