---
title: "Optimal and robust combination of forecasts via constrained optimization and shrinkage"
author: "[Frédéric Vrins](https://sites.google.com/view/fredericvrins)"
date: 2022-10-14
categories: [2022-2023, Quantact]
draft: 
room: "St-Hubert"
time: 15h00
url: https://sites.google.com/view/fredericvrins
---

# Résumé

We introduce various methods that combine forecasts using constrained optimization with penalty. A non-negativity constraint is imposed on the weights, and several penalties are considered, taking the form of a divergence from a reference combination scheme. In contrast with most of the existing approaches, our framework performs forecast selection and combination in one step, allowing for potentially sparse combining schemes. Moreover, by exploiting the analogy between forecasts combination and portfolio optimization, we provide the analytical expression of the optimal penalty strength when penalizing with the L2-divergence from the equally-weighted scheme. An extensive simulation study and two empirical applications allow us to investigate the impact of the divergence function, the reference scheme, and the non-negativity constraint on the predictive performance. Our results suggest that the proposed models outperform those considered in previous studies.

# Biographie

Frédéric Vrins a obtenu un PhD de l'École polytechnique de Louvain (UCLouvain) en 2007 dans le domaine du traitement de signaux adaptifs. Il a travaillé sur des méthodes de séparations de signaux dans le secteur biomédical, avant de se réorienter dans le secteur bancaire où il a travaillé comme analyste quantitatif pendant 7 ans. Depuis 2014, il est professeur titulaire au sein de l'institut de finance quantitative de l'École de gestion de Louvain, en plus d'être professeur affilié à HEC Montréal.
