---
title: "Disaster Resilient Cities: An OR Approach to Disaster Management"
author: "[Bahar Yetis Kara](https://ie.bilkent.edu.tr/~bkara/index.php)"
date: 2023-10-11
categories: [2023-2024,GERAD]
draft: false
room: "salle [Budapest](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/budapest.html)"
time: "13h00"
url: https://ie.bilkent.edu.tr/~bkara/index.php
---

# Résumé

There have been decades of research in the field of humanitarian logistics, and academics in the field of logistics are becoming more and more interested in it. That being said, we still acquire insight and identify new problems with each disaster. 

We have also observed various humanitarian logistics applications during Covid-19, e.g. for PCR test sites and vaccination centers. Unfortunately, the recent earthquake in Turkey has led us to re-evaluate the response cycle of disaster management. Close inspection reveals that this response phase actually leads to a variety of new applications of distribution logistics problems.  

We have conducted many meetings and workshops with municipalities that were very active during the response of the Maraş Earthquakes. Many municipalities  aim to have "earthquake resistant cities"  with correct action plans and being ready for potential disasters. Based on our discussions with these municipalities, we have developed an "ideal action plan". We also investigated the potential decision problems and linked these problems with OR literature.

# Biographie

Dr. Bahar Y. Kara est professeure titulaire au département de génie industriel de l'Université Bilkent, où elle a effectué toutes ses études et de laquelle elle a obtenu un doctorat sous la direction de B.C. Tansel en 1999. Elle a effectué un postdoctorat en gestion à McGill avant de retourner en Turquie. Ses intérêts de recherches sont en logistique, notamment logistique humanitaire et distribution, construction de réseau et problèmes de routages. Dr. Kara est membre fondatrice du comité exécutive EURO pour les opérations humanitaires (HOpe). Elle est également membre du conseil exécutif de l'Université Bilkent et la société turque de recherche opérationnelle. Dr. Kara a édité quatre ouvrages de référence et publié plus de 80 articles. Elle est rédactrice adjointe de *Transportation Research-Part B*, du *Journal of Operational Research Society*, de *IIE Transactions*, et de *Socio Economic Planning and Science*.
