---
title: "Learning to Simulate Tail-risk Scenarios"
author: "[Renyuan Xu](https://renyuanxu.github.io/)"
date: 2023-11-10
categories: [2023-2024,Quantact]
draft: false
room: "salle [Accra](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/accra.html)"
time: "13h00"
url: https://renyuanxu.github.io/
---

# Résumé

The estimation of loss distributions for dynamic portfolios requires the simulation of scenarios representing realistic joint dynamics of their components. Scalability to large or heterogeneous portfolios involving multiple asset classes is particularly challenging, as is the accurate representation of tail risk.
 
We propose a novel data-driven approach for the simulation of realistic multi-asset scenarios with a particular focus on the accurate estimation of tail risk for a given class of static and dynamic portfolios selected by the user. By exploiting the joint elicitability property of Value-at-Risk (VaR) and Expected Shortfall (ES), we design a Generative Adversarial Network (GAN) architecture capable of learning to simulate price scenarios that preserve tail risk features for these benchmark trading strategies, leading to consistent estimators for their VaR and ES.
 
From a theoretical perspective, we show that different choices of score functions lead to different optimization landscapes and different complexities in GAN training. In addition, we prove that the generator in our GAN architecture enjoys a universal approximation property under the criteria of tail risk measures. In addition, we prove the bi-level optimization formulation between the generator and the discriminator is equivalent to a max-min game, leading to a more effective and practical formulation for training. From an empirical perspective, we demonstrate the accuracy and scalability of our method via extensive simulation experiments using synthetic and market data. Our results show that, in contrast to other data-driven scenario generators, our proposed scenario simulation method correctly captures tail risk for both static and dynamic portfolios in the input datasets.
 
This is based on joint work with Rama Cont, Mihai Cucuringu, and Chao Zhang (Oxford).

# Biographie

Dr. Renyuan Xu est professeure adjointe WiSE Gabilan au départment de génie industriel et des systèmes à l'Université de la Californie du Sud. Avant de se joindre à USC, elle a passé deux années à Oxford avec Rama Cont comme fellow de recherche. Renyuan a obtenu son doctorat de l'Université de la Californie à Berkeley en 2019. Ses intérêts de recherche sont en théorie du contrôle et des jeux stochastiques, l'apprentissage par renforcement et l'apprentissage automatique avec application en finance et dans les transactions à haute fréquence.
