---
title: "Locating Facilities for Smart and Sustainable Mobility"
author: "[Sibel Alumur Alev](https://uwaterloo.ca/scholar/salumura/home)"
date: 2024-11-11
categories: [GERAD, 2024-2025]
draft: false
room: "salle [Florence](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/florence.html)"
time: "11h00"
url: https://uwaterloo.ca/scholar/salumura/home
---

# Résumé

This talk will explore three facility location problems for smart and sustainable mobility. The first problem focuses on locating and sizing charging stations to support long-distance travel with electric vehicles. A bilevel optimization model is developed where the network planner (leader) minimizes infrastructure costs while meeting probabilistic service requirements for waiting times to charge. Electric vehicle users (followers) minimize their route lengths, affecting charging demand and wait times. The bilevel problem is reduced to a single-level mixed-integer model when stations operate as M/M/c queues and users cooperate. A decomposition-based solution method is developed using a logic-based Benders algorithm. Computational experiments on benchmark and real-world highway networks analyze the impact of route choice, service requirements, and deviation tolerance on decisions. The second problem involves designing hub networks for the strategic deployment of autonomous shuttles. Given a set of passenger trips in an urban area, the goal is to determine the origins and destinations of a fixed number of hub arcs representing shuttle connections to maximize users of the system. This problem is formulated as a maximal covering hub arc location model and solved to optimality using Benders decomposition. Two data-driven clustering-based methodologies are also implemented and compared with the optimization model. Computational experiments using the New York City taxi data compare optimization and data-driven approaches on key performance metrics. The final problem addresses infrastructure design for shared autonomous transportation by locating staging facilities and deploying autonomous lanes. A bi-objective model is developed that minimizes total travel distance as well as non-autonomous lane travel, given a lane deployment budget and the number of staging facilities to locate. Trade-offs are evaluated on benchmark instances.

# Biographie

Dr. Alumur Alev is a tenured Associate Professor in the Department of Management Science and Engineering at the University of Waterloo. She received her Ph.D. degree in Industrial Engineering from Bilkent University in 2009 and subsequently served as a Post-Doctoral Researcher at the Institute of Operations Research at Karlsruhe Institute of Technology, Germany. Before joining the University of Waterloo in 2014, she worked as an Assistant Professor at TOBB University of Economics and Technology in Ankara. In 2017, she received the Chuck ReVelle Rising Star Award from the Institute for Operations Research and the Management Sciences (INFORMS) as a recognition of her research accomplishments in Location Analysis. In 2020, she received an Outstanding Performance Award at the University of Waterloo and in 2023, she was awarded the Engineering Research Excellence Award in recognition of her outstanding research accomplishments in the Faculty of Engineering.  She currently serves as the Senior Associate Editor for the journal Socio-Economic Planning Sciences, an Associate Editor for the journals Transportation Science and Service Science, an Editorial Board Editor for Transportation Research Part B, and an Editorial Board Member for Computers & Operations Research. Her research interests lie in optimizing facility locations and logistics operations, in particular, hub location, hub network design, supply chain and reverse logistics network design.
