---
title: "Biais de sélection et assurance : une structure de prime équitable pour un portefeuille est-elle globalement équitable sur le marché?"
author: "[Marie-Pier Côté](https://www.fsg.ulaval.ca/corps-professoral/marie-pier-cote)"
date: 2024-12-05
categories: [2024-2025]
draft: false
room: "salle [Hélène-Desmarais](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/hdesmarais.html)"
time: "11h00"
url: https://www.fsg.ulaval.ca/corps-professoral/marie-pier-cote
---

# Résumé






L'équité est centrée sur les personnes. Dans le domaine de l'assurance, elle devrait s'appliquer à l'ensemble de la population assurée, et non seulement aux clients d'un assureur. Toutefois, le portefeuille de chaque compagnie représente un sous-échantillon souvent non-représentatif. Un modèle ajusté sur ces données, empreintes d’un biais de sélection, se généralise mal à l’ensemble des assurés. Deux biais découlent de la composition du portefeuille : le biais de représentation, lorsque des erreurs importantes sont commises sur les prévisions pour les individus appartenant à des sous-populations rarement observées, et le biais de sélection, lorsque les pratiques de souscription des risques et de marketing rendent le portefeuille différent de la population assurée. Nous examinons comment la composition du portefeuille affecte les méthodologies de primes équitables pour atténuer la discrimination directe et indirecte sur la base d'un attribut protégé. Nous illustrons comment l'atténuation des iniquités basée sur des portefeuilles biaisés ne produit pas un marché équitable pour les assurés. En nous appuyant sur l'inférence causale et sur un indicateur de composition du portefeuille, nous décrivons le mécanisme de sélection et identifions les conditions pour lesquelles chaque biais affecte les primes équitables selon différentes méthodologies. Enfin, nous proposons une méthode pour corriger le biais des primes équitables calculées sur un portefeuille spécifique, en utilisant une estimation sans biais (fournie par un tiers) de la distribution des attributs interdits. Cette approche atténue efficacement le biais de sélection mais conduit à des primes globales qui ne sont pas équilibrées sur le portefeuille.

<!--
Selection bias in insurance: why portfolio-specific fairness fails to extend market-wide

Fairness centres on people. In insurance, the scope of fairness is the entire insured population, not solely an insurer’s clients. However, each insurance company’s portfolio represents a skewed subsample. Models fit to these selection-biased data do not generalize well for the broader population of insureds. Two biases stem from portfolio composition: representation bias, when large prediction errors are made on individuals from subpopulations infrequently observed, and selection bias, when underwriting and marketing skew the portfolio away from the insured population. We examine how portfolio composition affects fair premium methodologies for mitigating direct and indirect discrimination on a protected attribute. We illustrate how unfairness mitigation based on a selection-biased portfolio does not yield a fair market from the perspective of insureds. Relying on causal inference and a portfolio composition indicator, we describe the selection mechanism and determine conditions under which each bias affects various fairness-adjusted premiums. We propose a method to recover the population-wide fairness-adjusted premiums from selection-biased data, by using a (third-party provided) unbiased estimate of the prohibited attribute distribution. We show that this approach effectively mitigates selection bias but leads to overall premiums that are not balanced. In a limiting case, we show that portfolio-specific fairness-aware premiums can lead to a market-wide unawareness strategy: portfolio composition opens the back door to proxy discrimination.
-->

# Biographie

Marie-Pier Côté est professeure agrégée à l'École d'actuariat de l'Université Laval depuis 2018, et titulaire de la Chaire de leadership en enseignement en analyse de données massives pour l'actuariat - Intact. Elle détient un doctorat en statistique de l'Université McGill (2018) et est membre Fellow de la Société des actuaires. Ses travaux de recherche sur l'apprentissage statistique en actuariat lui ont valu le prix du meilleur article publié en 2021 dans le North American Actuarial Journal et le prix Patrick Brockett & Arnold Shapiro Award de l'American Risk and Insurance Association. Elle s'intéresse notamment à l'équité algorithmique en actuariat et à la modélisation statistique de la dépendance et des risques actuariels.
