---
title: "Scalable Bayesian design for business innovation"
author: "[Luke Hagar](https://lmhagar.github.io/)"
date: 2024-11-22
categories: [2024-2025]
draft: false
room: "salle [Paris](https://www.hec.ca/campus/cote_sainte_catherine/3e_etage/salles_cours/paris.html)"
time: "14h00"
url: https://lmhagar.github.io/
---

# Résumé


Abstract: Trustworthy Bayesian studies can be designed to satisfy criteria for operating characteristics of posterior analyses – such as power and the type I error rate. Such studies may inform decision-making processes in business analytics, marketing strategies, and product development. Operating characteristics for posterior analyses are typically assessed by exploring entire sampling distributions of posterior probabilities via simulation. We propose a scalable method to determine optimal sample sizes and decision criteria that maps posterior probabilities to low-dimensional conduits for the data. Our method leverages this mapping and large-sample theory to explore segments of the relevant sampling distributions. This approach prompts consistent sample size recommendations with fewer simulation repetitions than standard methods. We repurpose the posterior probabilities computed in that approach to efficiently investigate various sample sizes and decision criteria using contour plots.

# Biographie

Dr. Luke Hagar is a postdoctoral fellow at McGill University. He obtained a PhD degree in statistics in 2024 from Waterloo, completed under the supervision of Nathaniel Stevens. Luke works in the field of experimental design: his research interests revolve around  efficient sampling techniques, hypothesis testing, Bayesian methods, and computational inference.
