---
title: "0DTE Option Pricing"
author: "[Roberto Renò](https://sites.google.com/essec.edu/reno/)"
date: 2024-09-24
categories: [2024-2025]
draft: false
room: "salle [Québecor](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/quebecor.html)"
time: "14h00"
url: https://sites.google.com/essec.edu/reno/
---

# Résumé

The market for ultra short-tenor (zero days-to-expiry or 0DTE) options has grown exponentially over the last few years. In 2023, daily volume in 0DTEs reached over 45% of overall daily option volume. After briefly describing this exploding new market, we present a novel pricing formula designed to capture the shape of the 0DTE implied volatility surface. Pricing hinges on an Edgeworth-like expansion of the conditional characteristic function of the continuous portion of the underlying’s price process. The expansion shifts probability mass from an otherwise locally Gaussian return density by adding time-varying skewness (through leverage) and time-varying kurtosis (through the volatility-of-volatility). The expansion is local in time and, therefore, naturally suited to price ultra short-tenor instruments, like 0DTEs. We document considerable (1) price and (2) hedging improvements as compared to state-of-the-art specifications. We conclude by providing suggestive results on nearly instantaneous predictability by estimating 0DTE-based return/variance risk premia. This is joint work with Federico M. Bandi and
Nicola Fusari.  The paper is available at [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4503344).

# Biographie

Roberto Renò is Professor at the IDS Department (Information Systems, Decision Sciences and Statistics) at ESSEC Business School. He is a former professor  Quantitative Finance at the University of Siena. He holds a PhD in Financial Mathematics at Scuola Normale Superiore in Pisa, and a Degree in Physics at the University of Pisa. His research focuses on various aspects of econometrics and finance, with specific contributions in asset pricing, high frequency financial econometrics, nonparametric statistics. 
