---
title: "An exploration-agnostic characterization of the ergodicity of parallel tempering"
author: "[Trevor Campbell](https://trevorcampbell.me/)"
date: 2024-01-26
categories: [2023-2024, CSMQ]
draft: false
room: "salle [Tkaronto](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/tkaronto.html)"
time: "15h30"
url: https://trevorcampbell.me/
---

# Résumé

Non-reversible parallel tempering (NRPT) is an effective algorithm for sampling from target distributions with complex geometry, such as those arising from posterior distributions of weakly identifiable and high-dimensional Bayesian models. In this talk I will establish the uniform geometric ergodicity of NRPT under an efficient local exploration hypothesis, which avoids the intricacies of dealing with kernel-specific properties. The rates that we obtain are bounded in terms of an easily-estimable divergence, the global communication barrier (GCB), that was recently introduced in the literature. We obtain analogous ergodicity results for classical reversible parallel tempering, providing new evidence that NRPT dominates its reversible counterpart. I will also present some general properties of the GCB and bound it in terms of the total variation distance and the inclusive/exclusive Kullback-Leibler divergences. I will conclude the talk with simulations that validate the new theoretical analysis.

This is based on joint work with Nikola Surjanovic, Saifuddin Syed, and Alexandre Bouchard-Côté.


# Biographie


Dr. Trevor Campbell est professeur agrégé au département de statistique de l'Université de la Colombie-Britannique à Vancouver. Ses recherches portent sur l'inférence Bayésienne, notamment le développement d'algorithmes flexible et automatisés, les données en lignes, la théorie bayésienne et les méthodes bayésiennes nonparamétriques. Trevor a complété son doctorat au Laboratoire d'information et de systèmes de décision au MIT sous la tutelle de Jonathan How et un stage postdoctoral avec Tamara Broderick.
