---
title: "Transmission planning in an imperfectly competitive power sector with environmental externalities "
author: "[Afzal Siddiqui](https://www.su.se/english/profiles/asidd-1.189734)"
date: 2024-10-11
categories: [2024-2025,Chaire de gestion du secteur de l’énergie]
draft: false
room: "salle [BMO](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/bmo.html)"
time: "13h00"
url: https://www.su.se/english/profiles/asidd-1.189734
---

# Résumé

Policymakers face the challenge of integrating intermittent output from variable renewable energy (VRE). Even in a well-functioning power sector with flexible generation, producers' incentives may not align with society's welfare-maximisation objective. At the same time, political pressure can obstruct policymakers from pricing damage from CO2 emissions according to its social costs. In facilitating decarbonisation, transmission planning will have to adapt to such economic and environmental distortions. Using a Stackelberg model of the Nordic power sector, we find that a first-best transmission-expansion plan involves better resource sharing between zones, which actually reduces the need for some VRE adoption. Next, we allow for departures from perfect competition and identify an extended transmission-expansion plan under market power by nuclear plants. By contrast, temporal arbitrage by hydro reservoirs does not necessitate transmission expansion beyond that of perfect competition because it incentivises sufficient VRE adoption using existing lines. Meanwhile, incomplete CO2 pricing under perfect competition requires a transmission plan that matches hydro-rich zones with sites for VRE adoption. However, since incomplete CO2 pricing leaves fossil-fuelled generation economically viable, it reduces the leverage of strategic producers, thereby catalysing less (more) extensive transmission expansion under market power by nuclear (hydro) plants.

# Biographie

Dr. Afzal S. Siddiqui est titulaire d’un doctorat en génie industriel et opérations de l’Université de la Californie à Berkeley et est professeur au département de science et systèmes informatiques de l’Université de Stockholm. Il était précédemment professeur d’économie de l’énergie au département des sciences statistique de UCL et professeur affilié à Aalto et HEC Montréal. Ses intérêts de recherche sont dans l’application des méthodes de recherche opérationnelle pour l’analyse de la prise de décision dans un contexte d’incertitude et de compétition dans le secteur énergétique.
