---
title: "Investigating Two-Stage Robust Optimization and Distributionally Robust Optimization from the Primal Perspective: A Complete and Intuitive Solution Framework"
author: "[Bo Zeng](https://www.engineering.pitt.edu/people/faculty/bo-zeng/)"
date: 2025-03-21
categories: [2024-2025]
draft: false
room: "salle [Associations étudiantes](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/associations-etudiantes.html)"
time: "11h00"
url: https://www.engineering.pitt.edu/people/faculty/bo-zeng/
---

# Résumé

Robust optimization (RO) and distributionally robust optimization (DRO), as relatively new optimization schemes, have been adopted in many practical systems (e.g., power, logistics and healthcare systems) to support their design, operations, and reliabilities. Conventionally, due to the sophisticated and nested min-max structures, two-stage RO and DRO are often studied using duality-based techniques, aiming to simplify their structures and obtain monolithic reformulations. Nevertheless, research developed from such dual perspective is rather abstract and technically demanding, which is less friendly to build intuitive understanding.  

In this talk, unlike existing research, we take the primal perspective to analyze RO and DRO, and directly make use of their primal structures to develop computational algorithms. The resulting column-and-constraint generation algorithm and its variants are, overall, simple, intuitive, and application-friendly. Actually, they often drastically outperform existing solution methods. Extensions to handle *decision-dependent uncertainty (DDU)*, which is closely related to the phenomenon of the "*induced demand*", will also be discussed.  Demonstrations in logistics, production, and energy systems, along with computational results and managerial insights, are presented to help us appreciate RO and DRO and those solution methods in practice.

# Biographie

Dr. Zeng is an Associate Professor of Industrial Engineering in the Swanson School of Engineering at the University of Pittsburgh where he teaches and conducts research discrete and robust optimization, with applications in logistics, energy, and healthcare systems. Prior to that, Bo obtained his PhD from Purdue in 2007 and worked as an assistant professor of Industrial and Management Systems Engineering at the University of South Florida, from 2009 to 2015. 

Through his research, Dr. Zeng has developed several analytical operational models and algorithms (e.g., the basic column-and-constraint generation method and its variants) that have been extensively applied in energy, logistics and other critical infrastructure systems, to address real design and operational issues and to hedge against risks and to achieve better reliability and security. He is a professional member of IISE, INFORMS and IEEE. 
