---
title: "A Generalized Logrank-type Test for Comparison of Treatment Regimes in Sequential Multiple Assignment Randomized Trials"
author: "[Marie Davidian](https://statistics.sciences.ncsu.edu/people/davidian/)"
date: 2025-01-24
categories: [CSMQ,2024-2025]
draft: false
room: "Zoom"
time: "15h30"
url: https://statistics.sciences.ncsu.edu/people/davidian/
---

# Résumé



The sequential multiple assignment randomized trial (SMART) is the gold standard study design for the evaluation of multistage treatment regimes, which comprise sequential decision rules that recommend treatments for a patient at each of a series of decision points based on their evolving characteristics. A common goal is to compare the set of so-called embedded regimes represented in the design on the basis of a primary outcome of interest. In the study of chronic diseases and disorders, this outcome is often a time to an event, and a goal is to compare the distributions of the time-to-event outcome associated with each regime in the set. We present a general statistical framework in which we develop a logrank-type test for comparison of the survival distributions associated with regimes within a specified set based on the data from a SMART with an arbitrary number of stages that allows incorporation of covariate information to enhance efficiency and can also be used with data from an observational study. The framework provides clarification of the assumptions required to yield a principled test procedure, and the proposed test subsumes or offers an improved alternative to existing methods. The methods are applied to a SMART in patients with acute promyelocytic leukemia. This is joint work with Anastasios A. Tsiatis.

 

# Biographie

Marie Davidian is J. Stuart Hunter Distinguished Professor of
Statistics at North Carolina State University (NC State) and Adjunct
Professor of Biostatistics and Bioinformatics at Duke University. Her
research interests include methodology for the design and analysis of
clinical trials and observational studies, for causal inference and
dynamic treatment regimes, for analysis of missing and mismeasured
data, and for longitudinal data analysis. Marie is a Fellow of the
American Statistical Association (ASA), Institute of Mathematical
Statistics (IMS), and the American Association for the Advancement of
Science, and an elected member of the International Statistical
Institute. Marie has received several awards and recognitions,
including the ASA Award for Outstanding Statistical Application
(1993), the Janet L. Norwood Award for Outstanding Achievement by a
Woman in the Statistical Science, the Committee of Presidents of
Statistical Societies (COPSS) Florence Nightingale David Award, the
COPSS George W. Snedecor Award, the ASA Founders Award, and the Marvin
Zelen Leadership Award in Statistical Science from the Harvard T. H.
Chan School of Public Health; as well as honorary life memberships in
the IMS and Interational Biometric Society. She has been Coordinating
and Executive Editor of the journal Biometrics, served on several US
Food and Drug Administration Advisory Committees, and served on
several US National Institutes of Health (NIH) grant review panels,
including as Chair of the Biostatistical Methods and Research Design
Study Section. Marie has published over 135 refereed papers and
several books. She has supervised over 30 PhD students. For two
decades, Marie was Program Director for the Summer Institute for
Biostatistics (SIBS), which introduced talented US undergraduates to
careers in biostatistics and encouraged them to pursue graduate
training; and an NIH predoctoral training grant, which placed PhD
students at NC State and Duke with cardiovascular disease research
projects at Duke Clinical Research Institute, providing them hands-on
collaborative experience in health sciences research. 
