---
title: "Fair Pricing Strategy"
author: "[Adam Elmachtoub](https://www.engineering.columbia.edu/faculty-staff/directory/adam-elmachtoub)"
date: 2025-11-07
categories: [2025-2026]
draft: false
room: "salle [Hélène-Desmarais](https://www.hec.ca/campus/cote_sainte_catherine/1er_etage/salles_cours/hdesmarais.html)"
time: "10:30"
url:  https://www.engineering.columbia.edu/faculty-staff/directory/adam-elmachtoub
---

# Résumé

Price discrimination strategies, which offer different prices to customers based on differences in their valuations, have become common practice. While it allows sellers to increase their profits, it also raises several concerns in terms of fairness, e.g., by charging higher prices (or denying access) to protected groups. This topic has received extensive attention from media, industry, and regulatory agencies. In this talk, we consider the problem of setting prices for different groups under fairness constraints, and the corresponding impact it has on consumer surplus and social welfare.

# Biographie

Adam Elmachtoub is an Associate Professor of Industrial Engineering and Operations Research at Columbia University, where he is also a member of the Data Science Institute.
He is also an Amazon Visiting Academic. His research spans two major themes: (i) designing machine learning and personalization methods to make informed decisions in industries such as retail, logistics, and travel (ii) new models and algorithms for revenue and supply chain management in modern e-commerce and service systems. He received his B.S. degree from Cornell and his Ph.D. from MIT ORC, both in operations research. He spent one year as a postdoc at the IBM T.J. Watson Research Center working in the area of Smarter Commerce. He has received an NSF CAREER Award, IBM Faculty Award, 1st place in the INFORMS JFIG (Junior Faculty) Paper Competition, Great Teacher Award from the Society of Columbia Graduates, and was on Forbes 30 under 30 in science.