---
title: ""
author: "[Serge Darolles](https://dauphine.psl.eu/recherche/cvtheque/darolles-serge)"
date: 2023-10-13
categories: [2023-2024]
draft: true
room: "salle à déterminer"
time: ""
url: https://dauphine.psl.eu/recherche/cvtheque/darolles-serge
---

# Résumé


# Biographie


Serge Darolles est Professeur de Finance à l'Université Paris-Dauphine où il enseigne l'économétrie de la finance et la finance empirique depuis 2012. Avant de rejoindre Dauphine, il a travaillé pour Lyxor Asset Management entre 2000 et 2012, où il a développé des modèles mathématiques pour diverses stratégies d’investissement. Il a également occupé des postes de consultants à la Caisse des Dépôts et Consignations, la Banque Paribas et le Commissariat à l'Energie Atomique. Serge est spécialisée est spécialisé en économétrie de la finance et a écrit de nombreux articles publiés dans de nombreuses revues académiques. Il est également membre du Conseil consultatif scientifique de l'AMF. Serge est titulaire d'un doctorat en mathématiques appliquées de l'Université de Toulouse et d'un DESS de l'ENSAE, Paris.


